wandb_version: 1

epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719306070.293047
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 54
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 54
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      4: 3.11.7
      5: 0.15.4
      8:
      - 1
      - 5
